# Generated by Django 5.2.5 on 2025-08-28 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('miqdor', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('umumiy_narx', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Haydovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('tel_raqam', models.CharField(max_length=15)),
                ('smena', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('tel_raqam', models.CharField(max_length=15)),
                ('manzil', models.CharField(max_length=255)),
                ('qarz', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=255)),
                ('narx', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('litr', models.PositiveSmallIntegerField()),
                ('batafsil', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
